all:V: qget qconsume basic 1p1c 2p1c 1p2c 2p2c

qconsume: qio.5 stuff.5 qconsume.5
	5l -o qconsume qio.5 stuff.5 qconsume.5

basic: qio.5 stuff.5 basic.5
	5l -o basic qio.5 stuff.5 basic.5

qget: qio.5 stuff.5 qget.5
	5l -o qget qio.5 stuff.5 qget.5

qbread: qio.5 stuff.5 qbread.5
	5l -o qbread qio.5 stuff.5 qbread.5

qcopy: qio.5 stuff.5 qcopy.5
	5l -o qcopy qio.5 stuff.5 qcopy.5

qproduce: qio.5 stuff.5 qproduce.5
	5l -o qproduce qio.5 stuff.5 qproduce.5

qdiscard: qio.5 stuff.5 qdiscard.5
	5l -o qdiscard qio.5 stuff.5 qdiscard.5

1p1c: qio.5 stuff.5 1p1c.5
	5l -o 1p1c qio.5 stuff.5 1p1c.5

2p1c: qio.5 stuff.5 2p1c.5
    5l -o 2p1c qio.5 stuff.5 2p1c.5

1p2c: qio.5 stuff.5 1p2c.5
    5l -o 1p2c qio.5 stuff.5 1p2c.5

2p2c: qio.5 stuff.5 2p2c.5
    5l -o 2p2c qio.5 stuff.5 2p2c.5

qio.5: qio.c stuff.h stuff.c error.h fns.h portfns.h mem.h lib/libc.h lib/u.h dat.h portdat.h
	5c qio.c

stuff.5: qio.c stuff.h stuff.c error.h fns.h portfns.h mem.h lib/libc.h lib/u.h dat.h portdat.h
	5c stuff.c

1p1c.5: qio.c stuff.h stuff.c error.h fns.h portfns.h mem.h lib/libc.h lib/u.h dat.h portdat.h 1p1c.c
	5c 1p1c.c

2p1c.5: qio.c stuff.h stuff.c error.h fns.h portfns.h mem.h lib/libc.h lib/u.h dat.h portdat.h 2p1c.c
	5c 2p1c.c

1p2c.5: qio.c stuff.h stuff.c error.h fns.h portfns.h mem.h lib/libc.h lib/u.h dat.h portdat.h 1p2c.c
	5c 1p2c.c

2p2c.5: qio.c stuff.h stuff.c error.h fns.h portfns.h mem.h lib/libc.h lib/u.h dat.h portdat.h 2p2c.c
	5c 2p2c.c

basic.5: qio.c stuff.h stuff.c error.h fns.h portfns.h mem.h lib/libc.h lib/u.h dat.h portdat.h basic.c
	5c basic.c

qget.5: qio.c stuff.h stuff.c error.h fns.h portfns.h mem.h lib/libc.h lib/u.h dat.h portdat.h qget.c
	5c qget.c

qbread.5: qio.c stuff.h stuff.c error.h fns.h portfns.h mem.h lib/libc.h lib/u.h dat.h portdat.h qbread.c
	5c qbread.c

qcopy.5: qio.c stuff.h stuff.c error.h fns.h portfns.h mem.h lib/libc.h lib/u.h dat.h portdat.h qcopy.c
	5c qcopy.c

qconsume.5: qio.c stuff.h stuff.c error.h fns.h portfns.h mem.h lib/libc.h lib/u.h dat.h portdat.h basic.c
	5c qconsume.c

qproduce.5: qio.c stuff.h stuff.c error.h fns.h portfns.h mem.h lib/libc.h lib/u.h dat.h portdat.h qproduce.c
	5c qproduce.c

qdiscard.5: qio.c stuff.h stuff.c error.h fns.h portfns.h mem.h lib/libc.h lib/u.h dat.h portdat.h qdiscard.c
	5c qdiscard.c

clean: 
    rm -f *.5
    rm -f 1p1c
    rm -f 2p1c
    rm -f 1p2c
    rm -f 2p2c
    rm -f basic
    rm -f qconsume
    rm -f main
    rm -f qbread
    rm -f qcopy
    rm -f qproduce
    rm -f qdiscard
    rm -f qget

